#!/bin/bash

echo ""
echo "=============================================="
echo "   DECODED SECURITY - HASHING LAB v1.0"
echo "   Password Cracking: See It For Yourself"
echo "=============================================="
echo ""
echo "INCIDENT BRIEFING"
echo "-----------------"
echo "A company database has been breached."
echo "The attacker dumped the password hash file."
echo ""
echo "Your mission:"
echo "  1. Understand what you are looking at"
echo "  2. Crack the weak passwords"
echo "  3. Understand why some passwords resist cracking"
echo "  4. Learn what this means for real password policy"
echo ""
echo "Files available to you:"
echo "  /lab/hashes.txt       - The recovered password hashes"
echo "  /lab/wordlists/       - Your attack wordlist"
echo ""
echo "Tools installed:"
echo "  john                  - John the Ripper password cracker"
echo "  python3               - For generating your own hashes"
echo ""
echo "Stuck? Type: cat /lab/hints.txt"
echo ""
echo "Good luck, analyst."
echo "=============================================="
echo ""
